version: "2"
services:
  f8a-server-backbone:
    build:
      context: .
    network_mode: bridge
    entrypoint:
      - /bin/entrypoint.sh
    environment:
      BAYESIAN_GREMLIN_HTTP_SERVICE_HOST: "bayesian-gremlin-http"
      BAYESIAN_GREMLIN_HTTP_SERVICE_PORT: "8182"
      PGBOUNCER_SERVICE_HOST: "bayesian-pgbouncer"
      PGBOUNCER_SERVICE_PORT: "5432"
      LICENSE_SERVICE_HOST: "f8a-license-analysis"
      LICENSE_SERVICE_PORT: "6162"
      PGM_SERVICE_HOST: "bayesian-kronos"
      PGM_SERVICE_PORT : "6006"
      POSTGRESQL_USER: "user"
      POSTGRESQL_PASSWORD: "password"
      POSTGRESQL_DATABASE: "dbname"
      GEMINI_API_SERVICE_TIMEOUT: "60"
      GEMINI_API_SERVICE_PORT: "5000"
      NUMBER_WORKER_PROCESS: "2"
      CLASS_TYPE: "sync"
    ports:
      - "5000:5000"
